package com.heaven.hotel.model.admin;

import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Abstract base class for all report types.
 * OOP: Abstraction (abstract gatherData/formatOutput), Template Method Pattern (generate)
 */
public abstract class Report {

    private String reportId;
    private String generatedBy;     // userId of the admin who generated the report
    private String dateRange;       // human-readable range, e.g. "2025-01-01 to 2025-03-31"
    private String generatedDate;   // timestamp when generated

    protected LocalDate startDate;
    protected LocalDate endDate;
    private   String reportType;
    private   String title;
    private   String summary;

    private static final DateTimeFormatter DT_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    public Report() {}

    public Report(String reportId, String generatedBy, String dateRange) {
        this.reportId      = reportId;
        this.generatedBy   = generatedBy;
        this.dateRange     = dateRange;
        this.generatedDate = LocalDateTime.now().format(DT_FMT);
    }

    // ── Abstract methods (Abstraction) ────────────────────────────────────────

    /** Each subclass collects its own data from file storage */
    public abstract void gatherData();

    /** Each subclass formats its own report content */
    public abstract String formatOutput();

    // ── Template method (defines the algorithm skeleton) ─────────────────────

    /**
     * Template method — calls gatherData() then formatOutput().
     * Subclasses override the steps, not the overall sequence.
     */
    public void generate() {
        this.generatedDate = LocalDateTime.now().format(DT_FMT);
        gatherData();
        this.summary = formatOutput();
        System.out.println("=== Report Generated: " + reportId + " ===");
        System.out.println(summary);
    }

    /**
     * Saves the formatted report output to a .txt file.
     */
    public void export(String filename) {
        generate();
        String content = "Report: " + reportId + "\n"
                + "Generated by: " + generatedBy + "\n"
                + "Period: " + dateRange + "\n"
                + "Date: " + generatedDate + "\n"
                + "=".repeat(50) + "\n"
                + (summary != null ? summary : "");
        try (FileWriter fw = new FileWriter(filename)) {
            fw.write(content);
            System.out.println("Report exported to: " + filename);
        } catch (IOException e) {
            System.err.println("Failed to export report: " + e.getMessage());
        }
    }

    // ── Getters & Setters ─────────────────────────────────────────────────────

    public String getReportId()                { return reportId; }
    public void   setReportId(String id)       { this.reportId = id; }

    public String getGeneratedBy()             { return generatedBy; }
    public void   setGeneratedBy(String uid)   { this.generatedBy = uid; }

    public String getDateRange()               { return dateRange; }
    public void   setDateRange(String r)       { this.dateRange = r; }

    public String getGeneratedDate()           { return generatedDate; }
    public void   setGeneratedDate(String dt)  { this.generatedDate = dt; }

    public LocalDate getStartDate()            { return startDate; }
    public void   setStartDate(LocalDate d)    { this.startDate = d; }

    public LocalDate getEndDate()              { return endDate; }
    public void   setEndDate(LocalDate d)      { this.endDate = d; }

    public String getReportType()              { return reportType; }
    public void   setReportType(String t)      { this.reportType = t; }

    public String getTitle()                   { return title; }
    public void   setTitle(String t)           { this.title = t; }

    public String getSummary()                 { return summary; }
    public void   setSummary(String s)         { this.summary = s; }
}
